# name of the project with .xcodeproj extension
project 'resturantApp.xcodeproj'

# platform: ios is the iphone simulator version, not the version of xCode
platform :ios, '11.0'
use_frameworks!


# '~> ' contains the version of the pods, pod version have to compatible with xCode version and swift version
target 'resturantApp' do
    pod 'AlamofireImage', '~> 3.4'
    pod 'Moya', '~> 12.0'
end

# Added below from https://github.com/pichillilorenzo/flutter_inappbrowser/issues/15
# And https://stackoverflow.com/questions/50458556/flutter-swift-version-must-be-set-to-a-supported-value

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'  # required by simple_permission
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
