# name of the project with .xcodeproj extension
project 'resturantApp.xcodeproj'

# platform: ios is the iphone simulator version, not the version of xCode
platform :ios, '11.0'
use_frameworks!

target 'resturantApp' do
    pod 'AlamofireImage'
    pod 'Moya'
end
